import type { Config } from 'tailwindcss'

// Exact Tailwind config from Stitch "Paper Magic" design system
const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container':           '#1a3a2a',
        'surface-dim':                 '#dadad8',
        'on-secondary-container':      '#763412',
        'inverse-surface':             '#2f3130',
        'primary-fixed-dim':           '#abcfb8',
        'error-container':             '#ffdad6',
        'tertiary-container':          '#31362c',
        'on-surface-variant':          '#424843',
        'on-primary-container':        '#82a48f',
        'surface-container-highest':   '#e2e3e1',
        'background':                  '#f9f9f7',
        'surface-container-high':      '#e8e8e6',
        'tertiary-fixed':              '#e0e4d6',
        'on-tertiary-fixed':           '#181d14',
        'on-primary-fixed-variant':    '#2d4d3c',
        'on-tertiary':                 '#ffffff',
        'surface-tint':                '#456553',
        'primary':                     '#032416',
        'on-error':                    '#ffffff',
        'error':                       '#ba1a1a',
        'surface':                     '#f9f9f7',
        'tertiary':                    '#1c2118',
        'surface-container':           '#eeeeec',
        'on-secondary-fixed':          '#360f00',
        'on-error-container':          '#93000a',
        'inverse-primary':             '#abcfb8',
        'on-secondary':                '#ffffff',
        'surface-container-lowest':    '#ffffff',
        'surface-variant':             '#e2e3e1',
        'tertiary-fixed-dim':          '#c4c8ba',
        'outline':                     '#727973',
        'inverse-on-surface':          '#f1f1ef',
        'on-primary':                  '#ffffff',
        'on-surface':                  '#1a1c1b',
        'on-tertiary-container':       '#9a9f91',
        'surface-bright':              '#f9f9f7',
        'secondary-fixed-dim':         '#ffb596',
        'secondary':                   '#934a27',  // terracotta — links, CTA button
        'secondary-container':         '#fd9e75',
        'surface-container-low':       '#f4f4f2',
        'primary-fixed':               '#c7ebd4',
        'secondary-fixed':             '#ffdbcd',
        'on-background':               '#1a1c1b',
        'on-secondary-fixed-variant':  '#763312',
        'on-tertiary-fixed-variant':   '#43483e',
        'outline-variant':             '#c1c8c2',
        'on-primary-fixed':            '#002113',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
      spacing: {
        'gutter':              '32px',
        'edge-margin-desktop': '64px',
        'stack-xl':            '64px',
        'edge-margin-mobile':  '24px',
        'stack-lg':            '32px',
        'container-max':       '1200px',
        'stack-sm':            '8px',
        'stack-md':            '16px',
      },
      fontFamily: {
        'lora':       ['Lora', 'serif'],
        'body-lg':    ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg':['Literata', 'serif'],
        'body-md':    ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md':['Literata', 'serif'],
        'display-lg-mobile': ['Literata', 'serif'],
        'caption':    ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg': ['Literata', 'serif'],
        'label-md':   ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'body-lg':    ['18px', {lineHeight:'30px', fontWeight:'400'}],
        'headline-lg':['32px', {lineHeight:'40px', fontWeight:'600'}],
        'body-md':    ['16px', {lineHeight:'26px', fontWeight:'400'}],
        'headline-md':['24px', {lineHeight:'32px', fontWeight:'600'}],
        'display-lg-mobile': ['36px', {lineHeight:'44px', letterSpacing:'-0.02em', fontWeight:'700'}],
        'caption':    ['12px', {lineHeight:'18px', fontWeight:'500'}],
        'display-lg': ['48px', {lineHeight:'56px', letterSpacing:'-0.02em', fontWeight:'700'}],
        'label-md':   ['14px', {lineHeight:'20px', letterSpacing:'0.05em', fontWeight:'600'}],
      },
      maxWidth: {
        'container-max': '1200px',
      },
    },
  },
  plugins: [],
}

export default config
